### ISSUE TITLE
line 58: unexpected EOF while looking for matching ``'

### ISSUE THREAD

**Issue by jon7797** [ImKKingshuk/StealthSQL#1]
At line 58 at the end of the dictionary definitions, the character " ` " is used which is being processed by bash as a control character. The way this is fixed is by putting a backslash (\) behind the character. 

Line 58 should be:

{ dictionary="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!\"#$%&'()*+,-./:;<=>?@[\\]^_\`{|}~" 
}

**Comment by ImKKingshuk** [comment]
Ok, I will check it.
